
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class account_table
{

    public int account_id { get; set; }

    public int patient_id { get; set; }

    public decimal amount { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public string remarks { get; set; }

    public string transaction_type { get; set; }

    public Nullable<int> Treat_crno { get; set; }

    public int Doctor_id { get; set; }

}

}
