
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class application_version
{

    public int version_id { get; set; }

    public string version { get; set; }

    public bool isForceful { get; set; }

    public System.DateTime version_date { get; set; }

}

}
