
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Appointment
{

    public int Id { get; set; }

    public System.DateTime DateStart { get; set; }

    public System.DateTime DateEnd { get; set; }

    public int DoctorId { get; set; }

    public int PatientId { get; set; }

    public string PatientName { get; set; }

    public string PatientMobile { get; set; }

    public string Relation { get; set; }

    public string Status { get; set; }

    public string SessionId { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.DateTime UpdatedDate { get; set; }

}

}
