

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ddiarydbEntities : DbContext
{
    public ddiarydbEntities()
        : base("name=ddiarydbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<OTPVerification> OTPVerifications { get; set; }

    public virtual DbSet<account_table> account_table { get; set; }

    public virtual DbSet<application_version> application_version { get; set; }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<Disease> Diseases { get; set; }

    public virtual DbSet<Doctor_Master> Doctor_Master { get; set; }

    public virtual DbSet<DoctorShift> DoctorShifts { get; set; }

    public virtual DbSet<Injury_Photos_Master> Injury_Photos_Master { get; set; }

    public virtual DbSet<Login_Master> Login_Master { get; set; }

    public virtual DbSet<Login_Track> Login_Track { get; set; }

    public virtual DbSet<Mail_Track> Mail_Track { get; set; }

    public virtual DbSet<medicine_table> medicine_table { get; set; }

    public virtual DbSet<monthly_sms> monthly_sms { get; set; }

    public virtual DbSet<Package_Assigned> Package_Assigned { get; set; }

    public virtual DbSet<Package_Master> Package_Master { get; set; }

    public virtual DbSet<Package_Requested> Package_Requested { get; set; }

    public virtual DbSet<Patient_Master> Patient_Master { get; set; }

    public virtual DbSet<prescription_table> prescription_table { get; set; }

    public virtual DbSet<Report_Problems_Mst> Report_Problems_Mst { get; set; }

    public virtual DbSet<SecurityAccount> SecurityAccounts { get; set; }

    public virtual DbSet<SecurityRole> SecurityRoles { get; set; }

    public virtual DbSet<Send_Mail> Send_Mail { get; set; }

    public virtual DbSet<SMS_Master> SMS_Master { get; set; }

    public virtual DbSet<Smtp_Mail_Master> Smtp_Mail_Master { get; set; }

    public virtual DbSet<symptom> symptoms { get; set; }

    public virtual DbSet<tblAddress> tblAddresses { get; set; }

    public virtual DbSet<Treatment_Image_Master> Treatment_Image_Master { get; set; }

    public virtual DbSet<Treatment_Master> Treatment_Master { get; set; }

    public virtual DbSet<usr> usrs { get; set; }

    public virtual DbSet<DoctorPatientMapping_Master> DoctorPatientMapping_Master { get; set; }

}

}

