
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class DoctorShift
{

    public int Id { get; set; }

    public int DoctorId { get; set; }

    public System.TimeSpan MorningStart { get; set; }

    public System.TimeSpan MorningEnd { get; set; }

    public System.TimeSpan AfternoonStart { get; set; }

    public System.TimeSpan AfternoonEnd { get; set; }

    public bool IsActive { get; set; }

}

}
