
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Login_Master
{

    public string stUserName { get; set; }

    public string stPhoneNo { get; set; }

    public string stPassword { get; set; }

    public string stEmail { get; set; }

    public int intUserId { get; set; }

}

}
