
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Mail_Track
{

    public int Id { get; set; }

    public Nullable<int> User_Id { get; set; }

    public string Email { get; set; }

    public string Verify_Code { get; set; }

    public Nullable<bool> IsSuccess { get; set; }

}

}
