
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class monthly_sms
{

    public long id { get; set; }

    public int user_id { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public int sms_count { get; set; }

    public int sms_remaining_count { get; set; }



    public virtual usr usr { get; set; }

}

}
