
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class OTPVerification
{

    public long Id { get; set; }

    public string MobileNo { get; set; }

    public string EmailId { get; set; }

    public string OTP { get; set; }

    public Nullable<bool> IsSMSSend { get; set; }

    public Nullable<bool> IsEmailSend { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

}

}
