
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Patient_Master
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patient_Master()
    {

        this.Treatment_Master = new HashSet<Treatment_Master>();

        this.Treatment_Master1 = new HashSet<Treatment_Master>();

    }


    public string Patient_state { get; set; }

    public string Patient_photo { get; set; }

    public string Patient_name { get; set; }

    public string Patient_email { get; set; }

    public string Patient_contact { get; set; }

    public string Patient_city { get; set; }

    public string Patient_address { get; set; }

    public int Patient_Id { get; set; }

    public string Patient_Country { get; set; }

    public Nullable<System.DateTime> Reg_Date { get; set; }

    public Nullable<int> User_Id { get; set; }

    public string note { get; set; }

    public Nullable<decimal> age { get; set; }

    public string gender { get; set; }

    public string relation { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual usr usr { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Treatment_Master> Treatment_Master { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Treatment_Master> Treatment_Master1 { get; set; }

}

}
