
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class prescription_table
{

    public int prescription_id { get; set; }

    public int Patient_Id { get; set; }

    public int Doctor_id { get; set; }

    public int Treat_crno { get; set; }

    public string medicine_name { get; set; }

    public string note { get; set; }

    public Nullable<bool> isMorning { get; set; }

    public Nullable<bool> isNoon { get; set; }

    public Nullable<bool> isEvening { get; set; }

    public Nullable<bool> isNight { get; set; }

    public string no_of_tablet { get; set; }

}

}
