
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class SecurityAccount
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SecurityAccount()
    {

        this.usrs = new HashSet<usr>();

    }


    public Nullable<int> RoleId { get; set; }

    public string passwd { get; set; }

    public string LoginName { get; set; }

    public byte IsActive { get; set; }

    public int Id { get; set; }



    public virtual SecurityRole SecurityRole { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<usr> usrs { get; set; }

}

}
