
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Send_Mail
{

    public Nullable<int> OutgoingPort { get; set; }

    public int ID { get; set; }

    public string HostName { get; set; }

    public string FromAddress { get; set; }

    public Nullable<bool> EnableSSL { get; set; }

    public string DisplayName { get; set; }

    public string AccountPassword { get; set; }

}

}
