
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class SMS_Master
{

    public long Id { get; set; }

    public int User_id { get; set; }

    public string Message { get; set; }

    public Nullable<bool> isDelivered { get; set; }

    public bool isMonthly { get; set; }

    public string To_Address { get; set; }

    public Nullable<System.DateTime> Date { get; set; }



    public virtual usr usr { get; set; }

}

}
