
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class symptom
{

    public long id { get; set; }

    public Nullable<long> d_id { get; set; }

    public string name { get; set; }

    public Nullable<long> user_id { get; set; }

}

}
