
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tblAddress
{

    public string State_Name { get; set; }

    public int Id { get; set; }

    public string Country_Name { get; set; }

    public string City_Name { get; set; }

}

}
