
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoctorDiaryAPI
{

using System;
    using System.Collections.Generic;
    
public partial class Treatment_Master
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Treatment_Master()
    {

        this.Injury_Photos_Master = new HashSet<Injury_Photos_Master>();

        this.Treatment_Image_Master = new HashSet<Treatment_Image_Master>();

    }


    public Nullable<System.DateTime> Treat_date { get; set; }

    public int Treat_crno { get; set; }

    public string SPO_two { get; set; }

    public string Remarks { get; set; }

    public string Patient_temp { get; set; }

    public string Patient_pulse { get; set; }

    public string Patient_image { get; set; }

    public string Patient_complain { get; set; }

    public Nullable<int> Patient_Id { get; set; }

    public string Patient_BP { get; set; }

    public string Medicine { get; set; }

    public Nullable<decimal> Counsultancyfee { get; set; }

    public string Advice { get; set; }

    public string Status { get; set; }

    public string Referred_Doctor_Name { get; set; }

    public string Referred_Hospital_Detail { get; set; }

    public string Patient_Report_Detail { get; set; }

    public Nullable<int> User_Id { get; set; }

    public bool Is_Paid { get; set; }

    public Nullable<System.DateTime> Follow_Date { get; set; }

    public Nullable<decimal> paid_Amount { get; set; }

    public Nullable<decimal> bill_Amount { get; set; }

    public string symptoms_id { get; set; }

    public string Prescription_Image { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Injury_Photos_Master> Injury_Photos_Master { get; set; }

    public virtual Patient_Master Patient_Master { get; set; }

    public virtual Patient_Master Patient_Master1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Treatment_Image_Master> Treatment_Image_Master { get; set; }

    public virtual usr usr { get; set; }

}

}
